{
 "title": "iMacs",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Сommon data",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 3, "x": 0, "y": 1 },
     "options": {
      "content": "<center>\n    <h1></h1>\n</center>"
     }
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 3, "x": 3, "y": 1 },
     "options": {
      "content": "<center>\n    <h1>COVID FREE</h1>\n</center>"
     }
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 3, "x": 6, "y": 1 },
     "options": {
      "content": "<center>\n    <h1>COVID BLOCK</h1>\n</center>"
     }
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 3, "x": 9, "y": 1 },
     "options": {
      "content": "<center>\n    <h1>OCCUPIED</h1>\n</center>"
     }
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 3, "x": 12, "y": 1 },
     "options": {
      "content": "<center>\n    <h1>AVAILABLE</h1>\n</center>"
     }
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 3, "x": 15, "y": 1 },
     "options": {
      "content": "<center>\n    <h1>DOWN</h1>\n</center>"
     }
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 3, "x": 18, "y": 1 },
     "options": {
      "content": "<center>\n    <h1>TOTAL</h1>\n</center>"
     }
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 3, "x": 0, "y": 3 },
     "options": {
      "content": "<center>\n    <h1>MIRAGE</h1>\n</center>"
     }
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 3, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "count(iMacService_status{job=\"iMacs\",instance=~\"mi-.*\",service=\"ldap\"} == 1) or on() vector(0)",
       "legendFormat": " "
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 6, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "count(iMacService_status{job=\"iMacs\",instance=~\"mi-.*\",service=\"ldap\"} == 0) or on() vector(0)",
       "legendFormat": " "
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 9, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "count(iMacUser_status{instance=~\"mi-.*\"} == 1) or on() vector(0)",
       "legendFormat": " "
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 12, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "(count(up{job=\"iMacs\",instance=~\"mi-.*\"})or on() vector(0)) - (count(iMacService_status{instance=~\"mi-.*\",service=\"ldap\"} == 0) or on() vector(0)) - (count(iMacUser_status{instance=~\"mi-.*\"} == 1) or on() vector(0)) >= 0 or on() vector(0)",
       "legendFormat": " "
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 15, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "(count(up{job=\"iMacs\",instance=~\"mi-.*\"} == 0) or on() vector(0))",
       "legendFormat": " "
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 18, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "(count(up{job=\"iMacs\",instance=~\"mi-.*\"}) or on() vector(0))",
       "legendFormat": " "
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 3, "x": 0, "y": 5 },
     "options": {
      "content": "<center>\n    <h1>ATLANTIS</h1>\n</center>"
     }
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 3, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "count(iMacService_status{job=\"iMacs\",instance=~\"at-.*\",service=\"ldap\"} == 1) or on() vector(0)",
       "legendFormat": " "
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 6, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "count(iMacService_status{job=\"iMacs\",instance=~\"at-.*\",service=\"ldap\"} == 0) or on() vector(0)",
       "legendFormat": " "
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 9, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "count(iMacUser_status{instance=~\"at-.*\"} == 1) or on() vector(0)",
       "legendFormat": " "
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 12, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "(count(up{job=\"iMacs\",instance=~\"at-.*\"})or on() vector(0)) - (count(iMacService_status{instance=~\"at-.*\",service=\"ldap\"} == 0) or on() vector(0)) - (count(iMacUser_status{instance=~\"at-.*\"} == 1) or on() vector(0))  >= 0 or on() vector(0)",
       "legendFormat": " "
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 15, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "(count(up{job=\"iMacs\",instance=~\"at-.*\"} == 0) or on() vector(0))",
       "legendFormat": " "
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 18, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "(count(up{job=\"iMacs\",instance=~\"at-.*\"}) or on() vector(0))",
       "legendFormat": " "
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 3, "x": 0, "y": 7 },
     "options": {
      "content": "<center>\n    <h1>OASIS</h1>\n</center>"
     }
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 3, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "count(iMacService_status{job=\"iMacs\",instance=~\"oa-.*\",service=\"ldap\"} == 1) or on() vector(0)",
       "legendFormat": " "
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 6, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "count(iMacService_status{job=\"iMacs\",instance=~\"oa-.*\",service=\"ldap\"} == 0) or on() vector(0)",
       "legendFormat": " "
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 9, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "count(iMacUser_status{instance=~\"oa-.*\"} == 1) or on() vector(0)",
       "legendFormat": " "
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 12, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "(count(up{job=\"iMacs\",instance=~\"oa-.*\"})or on() vector(0)) - (count(iMacService_status{instance=~\"oa-.*\",service=\"ldap\"} == 0) or on() vector(0)) - (count(iMacUser_status{instance=~\"oa-.*\"} == 1) or on() vector(0))  >= 0 or on() vector(0)",
       "legendFormat": " "
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 15, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "(count(up{job=\"iMacs\",instance=~\"oa-.*\"} == 0) or on() vector(0))",
       "legendFormat": " "
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 18, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "(count(up{job=\"iMacs\",instance=~\"oa-.*\"}) or on() vector(0))",
       "legendFormat": " "
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 3, "x": 0, "y": 9 },
     "options": {
      "content": "<center>\n    <h1>ILLUSION</h1>\n</center>"
     }
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 3, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "count(iMacService_status{job=\"iMacs\",instance=~\"il-.*\",service=\"ldap\"} == 1) or on() vector(0)",
       "legendFormat": " "
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 6, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "count(iMacService_status{job=\"iMacs\",instance=~\"il-.*\",service=\"ldap\"} == 0) or on() vector(0)",
       "legendFormat": " "
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 9, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "count(iMacUser_status{instance=~\"il-.*\"} == 1) or on() vector(0)",
       "legendFormat": " "
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 12, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "(count(up{job=\"iMacs\",instance=~\"il-.*\"})or on() vector(0)) - (count(iMacService_status{instance=~\"il-.*\",service=\"ldap\"} == 0) or on() vector(0)) - (count(iMacUser_status{instance=~\"il-.*\"} == 1) or on() vector(0)) >= 0 or on() vector(0)",
       "legendFormat": " "
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 15, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "(count(up{job=\"iMacs\",instance=~\"il-.*\"} == 0) or on() vector(0))",
       "legendFormat": " "
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 18, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "(count(up{job=\"iMacs\",instance=~\"il-.*\"}) or on() vector(0))",
       "legendFormat": " "
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 3, "x": 0, "y": 11 },
     "options": {
      "content": "<center>\n    <h1>GALAXY</h1>\n</center>"
     }
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 3, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "count(iMacService_status{job=\"iMacs\",instance=~\"ga-.*\",service=\"ldap\"} == 1) or on() vector(0)",
       "legendFormat": " "
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 6, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "count(iMacService_status{job=\"iMacs\",instance=~\"ga-.*\",service=\"ldap\"} == 0) or on() vector(0)",
       "legendFormat": " "
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 9, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "count(iMacUser_status{instance=~\"ga-.*\"} == 1) or on() vector(0)",
       "legendFormat": " "
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 12, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "(count(up{job=\"iMacs\",instance=~\"ga-.*\"}) or on() vector(0)) - (count(iMacService_status{instance=~\"ga-.*\",service=\"ldap\"} == 0) or on() vector(0)) - (count(iMacUser_status{instance=~\"ga-.*\"} == 1) or on() vector(0)) >= 0 or on() vector(0)",
       "legendFormat": " "
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 15, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "(count(up{job=\"iMacs\",instance=~\"ga-.*\"} == 0) or on() vector(0))",
       "legendFormat": " "
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 18, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "(count(up{job=\"iMacs\",instance=~\"ga-.*\"}) or on() vector(0))",
       "legendFormat": " "
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 3, "x": 0, "y": 13 },
     "options": {
      "content": "<center>\n    <h1>VOID</h1>\n</center>"
     }
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 3, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "count(iMacService_status{job=\"iMacs\",instance=~\"vo-.*\",service=\"ldap\"} == 1) or on() vector(0)",
       "legendFormat": " "
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 6, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "count(iMacService_status{job=\"iMacs\",instance=~\"vo-.*\",service=\"ldap\"} == 0) or on() vector(0)",
       "legendFormat": " "
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 9, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "count(iMacUser_status{instance=~\"vo-.*\"} == 1) or on() vector(0)",
       "legendFormat": " "
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 12, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "(count(up{job=\"iMacs\",instance=~\"vo-.*\"})or on() vector(0)) - (count(iMacService_status{instance=~\"vo-.*\",service=\"ldap\"} == 0) or on() vector(0)) - (count(iMacUser_status{instance=~\"vo-.*\"} == 1) or on() vector(0)) >= 0 or on() vector(0)",
       "legendFormat": " "
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 15, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "(count(up{job=\"iMacs\",instance=~\"vo-.*\"} == 0) or on() vector(0))",
       "legendFormat": " "
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 18, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "(count(up{job=\"iMacs\",instance=~\"vo-.*\"}) or on() vector(0))",
       "legendFormat": " "
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 3, "x": 0, "y": 15 },
     "options": {
      "content": "<center>\n    <h1>OXYGEN</h1>\n</center>"
     }
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 3, "y": 15 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "count(iMacService_status{job=\"iMacs\",instance=~\"ox-.*\",service=\"ldap\"} == 1) or on() vector(0)",
       "legendFormat": " "
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 6, "y": 15 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "count(iMacService_status{job=\"iMacs\",instance=~\"ox-.*\",service=\"ldap\"} == 0) or on() vector(0)",
       "legendFormat": " "
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 9, "y": 15 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "count(iMacUser_status{instance=~\"ox-.*\"} == 1) or on() vector(0)",
       "legendFormat": " "
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 12, "y": 15 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "(count(up{job=\"iMacs\",instance=~\"ox-.*\"})or on() vector(0)) - (count(iMacService_status{instance=~\"ox-.*\",service=\"ldap\"} == 0) or on() vector(0)) - (count(iMacUser_status{instance=~\"ox-.*\"} == 1) or on() vector(0)) >= 0 or on() vector(0)",
       "legendFormat": " "
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 15, "y": 15 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "(count(up{job=\"iMacs\",instance=~\"ox-.*\"} == 0) or on() vector(0))",
       "legendFormat": " "
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 18, "y": 15 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "(count(up{job=\"iMacs\",instance=~\"ox-.*\"}) or on() vector(0))",
       "legendFormat": " "
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 3, "x": 0, "y": 17 },
     "options": {
      "content": "<center>\n    <h1>SUPERNOVA</h1>\n</center>"
     }
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 3, "y": 17 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "count(iMacService_status{job=\"iMacs\",instance=~\"su-.*\",service=\"ldap\"} == 1) or on() vector(0)",
       "legendFormat": " "
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 6, "y": 17 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "count(iMacService_status{job=\"iMacs\",instance=~\"su-.*\",service=\"ldap\"} == 0) or on() vector(0)",
       "legendFormat": " "
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 9, "y": 17 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "count(iMacUser_status{instance=~\"su-.*\"} == 1) or on() vector(0)",
       "legendFormat": " "
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 12, "y": 17 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "(count(up{job=\"iMacs\",instance=~\"su-.*\"})or on() vector(0)) - (count(iMacService_status{instance=~\"su-.*\",service=\"ldap\"} == 0) or on() vector(0)) - (count(iMacUser_status{instance=~\"su-.*\"} == 1) or on() vector(0)) >= 0 or on() vector(0)",
       "legendFormat": " "
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 15, "y": 17 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "(count(up{job=\"iMacs\",instance=~\"su-.*\"} == 0) or on() vector(0))",
       "legendFormat": " "
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 18, "y": 17 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "(count(up{job=\"iMacs\",instance=~\"su-.*\"}) or on() vector(0))",
       "legendFormat": " "
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 3, "x": 0, "y": 19 },
     "options": {
      "content": "<center>\n    <h1>ATRIUM</h1>\n</center>"
     }
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 3, "y": 19 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "count(iMacService_status{job=\"iMacs\",instance=~\"am-.*\",service=\"ldap\"} == 1) or on() vector(0)",
       "legendFormat": " "
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 6, "y": 19 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "count(iMacService_status{job=\"iMacs\",instance=~\"am-.*\",service=\"ldap\"} == 0) or on() vector(0)",
       "legendFormat": " "
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 9, "y": 19 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "count(iMacUser_status{instance=~\"am-.*\"} == 1) or on() vector(0)",
       "legendFormat": " "
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 12, "y": 19 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "(count(up{job=\"iMacs\",instance=~\"am-.*\"})or on() vector(0)) - (count(iMacService_status{instance=~\"am-.*\",service=\"ldap\"} == 0) or on() vector(0)) - (count(iMacUser_status{instance=~\"am-.*\"} == 1) or on() vector(0)) >= 0 or on() vector(0)",
       "legendFormat": " "
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 15, "y": 19 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "(count(up{job=\"iMacs\",instance=~\"am-.*\"} == 0) or on() vector(0))",
       "legendFormat": " "
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 18, "y": 19 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "(count(up{job=\"iMacs\",instance=~\"am-.*\"}) or on() vector(0))",
       "legendFormat": " "
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 3, "x": 0, "y": 21 },
     "options": {
      "content": "<center>\n    <h1>PLASMA</h1>\n</center>"
     }
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 3, "y": 21 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "count(iMacService_status{job=\"iMacs\",instance=~\"pl-.*\",service=\"ldap\"} == 1) or on() vector(0)",
       "legendFormat": " "
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 6, "y": 21 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "count(iMacService_status{job=\"iMacs\",instance=~\"pl-.*\",service=\"ldap\"} == 0) or on() vector(0)",
       "legendFormat": " "
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 9, "y": 21 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "count(iMacUser_status{instance=~\"pl-.*\"} == 1) or on() vector(0)",
       "legendFormat": " "
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 12, "y": 21 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "(count(up{job=\"iMacs\",instance=~\"pl-.*\"})or on() vector(0)) - (count(iMacService_status{instance=~\"pl-.*\",service=\"ldap\"} == 0) or on() vector(0)) - (count(iMacUser_status{instance=~\"pl-.*\"} == 1) or on() vector(0)) >= 0 or on() vector(0)",
       "legendFormat": " "
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 15, "y": 21 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "(count(up{job=\"iMacs\",instance=~\"pl-.*\"} == 0) or on() vector(0))",
       "legendFormat": " "
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 18, "y": 21 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "(count(up{job=\"iMacs\",instance=~\"pl-.*\"}) or on() vector(0))",
       "legendFormat": " "
      }
     ]
    }
   ]
  },
  {
   "title": "Drop",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Drop",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "up{job=\"iMacs\"} == 0"
      }
     ]
    }
   ]
  },
  {
   "title": "Third floor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Galaxy",
     "type": "table",
     "gridPos": { "h": 11, "w": 23, "x": 0, "y": 24 },
     "targets": [
      {
       "expr": "iMacUser_status{instance=~\"ga-.*\"}"
      },
      {
       "expr": "cpu_usage_procent{instance=~\"ga-.*\"}"
      },
      {
       "expr": "iMacTemp_cpuTemp{instance=~\"ga-.*\"}"
      },
      {
       "expr": "iMacTemp_fan{instance=~\"ga-.*\"}"
      },
      {
       "expr": "iMacTemp_gpuTemp{instance=~\"ga-.*\"}"
      },
      {
       "expr": "mem_used_percent{instance=~\"ga-.*\"}"
      },
      {
       "expr": "iMacPeriphery_status{instance=~\"ga-.*\",Type=\"Keyboard\"}"
      },
      {
       "expr": "iMacPeriphery_status{instance=~\"ga-.*\",Type=\"Mouse\"}"
      }
     ]
    },
    {
     "title": "Void",
     "type": "table",
     "gridPos": { "h": 11, "w": 23, "x": 0, "y": 35 },
     "targets": [
      {
       "expr": "iMacUser_status{instance=~\"vo-.*\"}"
      },
      {
       "expr": "cpu_usage_procent{instance=~\"vo-.*\"}"
      },
      {
       "expr": "iMacTemp_cpuTemp{instance=~\"vo-.*\"}"
      },
      {
       "expr": "iMacTemp_fan{instance=~\"vo-.*\"}"
      },
      {
       "expr": "iMacTemp_gpuTemp{instance=~\"vo-.*\"}"
      },
      {
       "expr": "mem_used_percent{instance=~\"vo-.*\"}"
      },
      {
       "expr": "iMacPeriphery_status{instance=~\"vo-.*\",Type=\"Keyboard\"}"
      },
      {
       "expr": "iMacPeriphery_status{instance=~\"vo-.*\",Type=\"Mouse\"}"
      }
     ]
    },
    {
     "title": "Oxygen",
     "type": "table",
     "gridPos": { "h": 11, "w": 23, "x": 0, "y": 46 },
     "targets": [
      {
       "expr": "iMacUser_status{instance=~\"ox-.*\"}"
      },
      {
       "expr": "cpu_usage_procent{instance=~\"ox-.*\"}"
      },
      {
       "expr": "iMacTemp_cpuTemp{instance=~\"ox-.*\"}"
      },
      {
       "expr": "iMacTemp_fan{instance=~\"ox-.*\"}"
      },
      {
       "expr": "iMacTemp_gpuTemp{instance=~\"ox-.*\"}"
      },
      {
       "expr": "mem_used_percent{instance=~\"ox-.*\"}"
      },
      {
       "expr": "iMacPeriphery_status{instance=~\"ox-.*\",Type=\"Keyboard\"}"
      },
      {
       "expr": "iMacPeriphery_status{instance=~\"ox-.*\",Type=\"Mouse\"}"
      }
     ]
    },
    {
     "title": "Supernova",
     "type": "table",
     "gridPos": { "h": 11, "w": 23, "x": 0, "y": 57 },
     "targets": [
      {
       "expr": "iMacUser_status{instance=~\"su-.*\"}"
      },
      {
       "expr": "cpu_usage_procent{instance=~\"su-.*\"}"
      },
      {
       "expr": "iMacTemp_cpuTemp{instance=~\"su-.*\"}"
      },
      {
       "expr": "iMacTemp_fan{instance=~\"su-.*\"}"
      },
      {
       "expr": "iMacTemp_gpuTemp{instance=~\"su-.*\"}"
      },
      {
       "expr": "mem_used_percent{instance=~\"su-.*\"}"
      },
      {
       "expr": "iMacPeriphery_status{instance=~\"su-.*\",Type=\"Keyboard\"}"
      },
      {
       "expr": "iMacPeriphery_status{instance=~\"su-.*\",Type=\"Mouse\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Second floor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Mirage",
     "type": "table",
     "gridPos": { "h": 11, "w": 23, "x": 0, "y": 25 },
     "targets": [
      {
       "expr": "iMacUser_status{instance=~\"mi-.*\"}"
      },
      {
       "expr": "cpu_usage_procent{instance=~\"mi-.*\"}"
      },
      {
       "expr": "iMacTemp_cpuTemp{instance=~\"mi-.*\"}"
      },
      {
       "expr": "iMacTemp_fan{instance=~\"mi-.*\"}"
      },
      {
       "expr": "iMacTemp_gpuTemp{instance=~\"mi-.*\"}"
      },
      {
       "expr": "mem_used_percent{instance=~\"mi-.*\"}"
      },
      {
       "expr": "iMacPeriphery_status{instance=~\"mi-.*\",Type=\"Keyboard\"}"
      },
      {
       "expr": "iMacPeriphery_status{instance=~\"mi-.*\",Type=\"Mouse\"}"
      }
     ]
    },
    {
     "title": "Atlantis",
     "type": "table",
     "gridPos": { "h": 11, "w": 23, "x": 0, "y": 36 },
     "targets": [
      {
       "expr": "iMacUser_status{instance=~\"at-.*\"}"
      },
      {
       "expr": "cpu_usage_procent{instance=~\"at-.*\"}"
      },
      {
       "expr": "iMacTemp_cpuTemp{instance=~\"at-.*\"}"
      },
      {
       "expr": "iMacTemp_fan{instance=~\"at-.*\"}"
      },
      {
       "expr": "iMacTemp_gpuTemp{instance=~\"at-.*\"}"
      },
      {
       "expr": "mem_used_percent{instance=~\"at-.*\"}"
      },
      {
       "expr": "iMacPeriphery_status{instance=~\"at-.*\",Type=\"Keyboard\"}"
      },
      {
       "expr": "iMacPeriphery_status{instance=~\"at-.*\",Type=\"Mouse\"}"
      }
     ]
    },
    {
     "title": "Oasis",
     "type": "table",
     "gridPos": { "h": 11, "w": 23, "x": 0, "y": 47 },
     "targets": [
      {
       "expr": "iMacUser_status{instance=~\"oa-.*\"}"
      },
      {
       "expr": "cpu_usage_procent{instance=~\"oa-.*\"}"
      },
      {
       "expr": "iMacTemp_cpuTemp{instance=~\"oa-.*\"}"
      },
      {
       "expr": "iMacTemp_fan{instance=~\"oa-.*\"}"
      },
      {
       "expr": "iMacTemp_gpuTemp{instance=~\"oa-.*\"}"
      },
      {
       "expr": "mem_used_percent{instance=~\"oa-.*\"}"
      },
      {
       "expr": "iMacPeriphery_status{instance=~\"oa-.*\",Type=\"Keyboard\"}"
      },
      {
       "expr": "iMacPeriphery_status{instance=~\"oa-.*\",Type=\"Mouse\"}"
      }
     ]
    },
    {
     "title": "Illusion",
     "type": "table",
     "gridPos": { "h": 11, "w": 23, "x": 0, "y": 58 },
     "targets": [
      {
       "expr": "iMacUser_status{instance=~\"il-.*\"}"
      },
      {
       "expr": "cpu_usage_procent{instance=~\"il-.*\"}"
      },
      {
       "expr": "iMacTemp_cpuTemp{instance=~\"il-.*\"}"
      },
      {
       "expr": "iMacTemp_fan{instance=~\"il-.*\"}"
      },
      {
       "expr": "iMacTemp_gpuTemp{instance=~\"il-.*\"}"
      },
      {
       "expr": "mem_used_percent{instance=~\"il-.*\"}"
      },
      {
       "expr": "iMacPeriphery_status{instance=~\"il-.*\",Type=\"Keyboard\"}"
      },
      {
       "expr": "iMacPeriphery_status{instance=~\"il-.*\",Type=\"Mouse\"}"
      }
     ]
    },
    {
     "title": "Atrium",
     "type": "table",
     "gridPos": { "h": 11, "w": 23, "x": 0, "y": 69 },
     "targets": [
      {
       "expr": "iMacUser_status{instance=~\"am-.*\"}"
      },
      {
       "expr": "cpu_usage_procent{instance=~\"am-.*\"}"
      },
      {
       "expr": "iMacTemp_cpuTemp{instance=~\"am-.*\"}"
      },
      {
       "expr": "iMacTemp_fan{instance=~\"am-.*\"}"
      },
      {
       "expr": "iMacTemp_gpuTemp{instance=~\"am-.*\"}"
      },
      {
       "expr": "mem_used_percent{instance=~\"am-.*\"}"
      },
      {
       "expr": "iMacPeriphery_status{instance=~\"am-.*\",Type=\"Keyboard\"}"
      },
      {
       "expr": "iMacPeriphery_status{instance=~\"am-.*\",Type=\"Mouse\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "First floor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Plasma",
     "type": "table",
     "gridPos": { "h": 11, "w": 23, "x": 0, "y": 26 },
     "targets": [
      {
       "expr": "iMacUser_status{instance=~\"pl-.*\"}"
      },
      {
       "expr": "cpu_usage_procent{instance=~\"pl-.*\"}"
      },
      {
       "expr": "iMacTemp_cpuTemp{instance=~\"pl-.*\"}"
      },
      {
       "expr": "iMacTemp_fan{instance=~\"pl-.*\"}"
      },
      {
       "expr": "iMacTemp_gpuTemp{instance=~\"pl-.*\"}"
      },
      {
       "expr": "mem_used_percent{instance=~\"pl-.*\"}"
      },
      {
       "expr": "iMacPeriphery_status{instance=~\"pl-.*\",Type=\"Keyboard\"}"
      },
      {
       "expr": "iMacPeriphery_status{instance=~\"pl-.*\",Type=\"Mouse\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Other data",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "OsVersion",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 6 },
     "targets": [
      { "expr": "iMacOsVersion_status", "legendFormat": "{{Version}}" }
     ]
    }
   ]
  }
 ]
}