{
 "title": "iMac",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "2m",
 "templating": {
  "list": [
   {
    "name": "Instance",
    "query": "label_values(iMacTemp_cpuTemp,  instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Login graph?",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "iMacUser_status{instance=\"$Instance\"}",
     "legendFormat": "{{login}}"
    }
   ]
  },
  {
   "title": "Login",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "iMacUser_status{instance=\"$Instance\"}",
     "legendFormat": "{{login}}"
    }
   ]
  },
  {
   "title": "Exam",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "iMacExam_status{instance=\"$Instance\"}"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "table",
   "gridPos": { "h": 7, "w": 10, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "disk_used{instance=\"$Instance\"}",
     "legendFormat": "{{path}}"
    },
    {
     "expr": "disk_total{instance=\"$Instance\"}",
     "legendFormat": "{{path}}"
    },
    {
     "expr": "(100 / disk_total{instance=\"$Instance\"}) * disk_used{instance=\"$Instance\"}",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Send packets",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(net_packets_sent{instance=\"$Instance\"}[1m])",
     "legendFormat": "{{interface}}"
    }
   ]
  },
  {
   "title": "OsVersion",
   "type": "stat",
   "description": "production(build) version",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "iMacOsVersion_status{instance=\"$Instance\"}",
     "legendFormat": "{{Version}}"
    }
   ]
  },
  {
   "title": "SerialNumber",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "iMacSerialNumber_status{instance=\"$Instance\"}",
     "legendFormat": "{{Serial}}"
    }
   ]
  },
  {
   "title": "Periphery",
   "type": "table",
   "gridPos": { "h": 7, "w": 10, "x": 6, "y": 14 },
   "targets": [
    {
     "expr": "iMacPeriphery_status{instance=\"$Instance\"}"
    }
   ]
  },
  {
   "title": "Send bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(net_bytes_sent{instance=\"$Instance\"}[1m])",
     "legendFormat": "{{interface}}"
    }
   ]
  },
  {
   "title": "Cpu Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cpu_usage_procent{instance=\"$Instance\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Mem Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "mem_used_percent{instance=\"$Instance\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Cpu Temp",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "iMacTemp_cpuTemp{instance=~\"$Instance\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Gpu Temp",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "iMacTemp_gpuTemp{instance=~\"$Instance\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Service",
   "type": "table",
   "gridPos": { "h": 7, "w": 10, "x": 6, "y": 21 },
   "targets": [
    {
     "expr": "iMacService_status{instance=\"$Instance\"}"
    }
   ]
  },
  {
   "title": "Recv packets",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(net_packets_recv{instance=\"$Instance\"}[1m])",
     "legendFormat": "{{interface}}"
    }
   ]
  },
  {
   "title": "Cpu usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "cpu_usage_procent{instance=\"$Instance\"}"
    }
   ]
  },
  {
   "title": "Cpu temp",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 28 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "iMacTemp_cpuTemp{instance=\"$Instance\"}"
    }
   ]
  },
  {
   "title": "Recv bytes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 28 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(net_bytes_recv{instance=\"$Instance\"}[1m])",
     "legendFormat": "{{interface}}"
    }
   ]
  },
  {
   "title": "Mem usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "mem_used_percent{instance=\"$Instance\"}"
    }
   ]
  },
  {
   "title": "Fans",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 34 },
   "yaxes": [
    { "format": "rotrpm" }
   ],
   "targets": [
    {
     "expr": "iMacTemp_fan{instance=\"$Instance\"}"
    }
   ]
  },
  {
   "title": "Net Error In",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "net_err_in{instance=\"$Instance\"}",
     "legendFormat": "{{interface}}"
    }
   ]
  },
  {
   "title": "Net Error Out",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "net_err_out{instance=\"$Instance\"}",
     "legendFormat": "{{interface}}"
    }
   ]
  },
  {
   "title": "Net Drop In",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "net_drop_in{instance=\"$Instance\"}",
     "legendFormat": "{{interface}}"
    }
   ]
  },
  {
   "title": "Net Drop Out",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "net_drop_out{instance=\"$Instance\"}",
     "legendFormat": "{{interface}}"
    }
   ]
  },
  {
   "title": "Periphery",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "iMacPeriphery_status{instance=\"$Instance\"}"
    }
   ]
  }
 ]
}