{
 "title": "iMacExam",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Сommon data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "type": "text", "gridPos": { "h": 2, "w": 3, "x": 0, "y": 1 }, "options": { "content": "<h1></h1>" } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 1 },
   "options": {
    "content": "<center>\n    <h1>EXAM</h1>\n</center>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 1 },
   "options": {
    "content": "<center>\n    <h1>NOT EXAM</h1>\n</center>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 1 },
   "options": {
    "content": "<center>\n    <h1>COVID FREE</h1>\n</center>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 1 },
   "options": {
    "content": "<center>\n    <h1>COVID BLOCK</h1>\n</center>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 1 },
   "options": {
    "content": "<center>\n    <h1>DOWN</h1>\n</center>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 1 },
   "options": {
    "content": "<center>\n    <h1>TOTAL</h1>\n</center>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 3 },
   "options": {
    "content": "<center>\n    <h1>MIRAGE</h1>\n</center>"
   }
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(iMacExam_status{instance=~\"mi-.*\"} == 1) or on() vector(0)",
     "legendFormat": " "
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(iMacExam_status{instance=~\"mi-.*\"} == 0) or on() vector(0)",
     "legendFormat": " "
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(iMacService_status{job=\"iMacs\",instance=~\"mi-.*\",service=\"ldap\"} == 1) or on() vector(0)",
     "legendFormat": " "
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(iMacService_status{job=\"iMacs\",instance=~\"mi-.*\",service=\"ldap\"} == 0) or on() vector(0)",
     "legendFormat": " "
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(up{job=\"iMacs\",instance=~\"mi-.*\"} == 0) or on() vector(0)",
     "legendFormat": " "
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(up{job=\"iMacs\",instance=~\"mi-.*\"}) or on() vector(0)",
     "legendFormat": " "
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 5 },
   "options": {
    "content": "<center>\n    <h1>ATLANTIS</h1>\n</center>"
   }
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(iMacExam_status{instance=~\"at-.*\"} == 1) or on() vector(0)",
     "legendFormat": " "
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(iMacExam_status{instance=~\"at-.*\"} == 0) or on() vector(0)",
     "legendFormat": " "
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(iMacService_status{job=\"iMacs\",instance=~\"at-.*\",service=\"ldap\"} == 1) or on() vector(0)",
     "legendFormat": " "
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(iMacService_status{job=\"iMacs\",instance=~\"at-.*\",service=\"ldap\"} == 0) or on() vector(0)",
     "legendFormat": " "
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(up{job=\"iMacs\",instance=~\"at-.*\"} == 0) or on() vector(0)",
     "legendFormat": " "
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(up{job=\"iMacs\",instance=~\"at-.*\"}) or on() vector(0)",
     "legendFormat": " "
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 7 },
   "options": {
    "content": "<center>\n    <h1>OASIS</h1>\n</center>"
   }
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(iMacExam_status{instance=~\"oa-.*\"} == 1) or on() vector(0)",
     "legendFormat": " "
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(iMacExam_status{instance=~\"oa-.*\"} == 0) or on() vector(0)",
     "legendFormat": " "
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(iMacService_status{job=\"iMacs\",instance=~\"oa-.*\",service=\"ldap\"} == 1) or on() vector(0)",
     "legendFormat": " "
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(iMacService_status{job=\"iMacs\",instance=~\"oa-.*\",service=\"ldap\"} == 0) or on() vector(0)",
     "legendFormat": " "
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(up{job=\"iMacs\",instance=~\"oa-.*\"} == 0) or on() vector(0)",
     "legendFormat": " "
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(up{job=\"iMacs\",instance=~\"oa-.*\"}) or on() vector(0)",
     "legendFormat": " "
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 9 },
   "options": {
    "content": "<center>\n    <h1>ILLUSION</h1>\n</center>"
   }
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(iMacExam_status{instance=~\"il-.*\"} == 1) or on() vector(0)",
     "legendFormat": " "
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(iMacExam_status{instance=~\"il-.*\"} == 0) or on() vector(0)",
     "legendFormat": " "
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(iMacService_status{job=\"iMacs\",instance=~\"il-.*\",service=\"ldap\"} == 1) or on() vector(0)",
     "legendFormat": " "
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(iMacService_status{job=\"iMacs\",instance=~\"il-.*\",service=\"ldap\"} == 0) or on() vector(0)",
     "legendFormat": " "
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(up{job=\"iMacs\",instance=~\"il-.*\"} == 0) or on() vector(0)",
     "legendFormat": " "
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(up{job=\"iMacs\",instance=~\"il-.*\"}) or on() vector(0)",
     "legendFormat": " "
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 11 },
   "options": {
    "content": "<center>\n    <h1>GALAXY</h1>\n</center>"
   }
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(iMacExam_status{instance=~\"ga-.*\"} == 1) or on() vector(0)",
     "legendFormat": " "
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(iMacExam_status{instance=~\"ga-.*\"} == 0) or on() vector(0)",
     "legendFormat": " "
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(iMacService_status{job=\"iMacs\",instance=~\"ga-.*\",service=\"ldap\"} == 1) or on() vector(0)",
     "legendFormat": " "
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(iMacService_status{job=\"iMacs\",instance=~\"ga-.*\",service=\"ldap\"} == 0) or on() vector(0)",
     "legendFormat": " "
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(up{job=\"iMacs\",instance=~\"ga-.*\"} == 0) or on() vector(0)",
     "legendFormat": " "
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(up{job=\"iMacs\",instance=~\"ga-.*\"}) or on() vector(0)",
     "legendFormat": " "
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 13 },
   "options": {
    "content": "<center>\n    <h1>VOID</h1>\n</center>"
   }
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(iMacExam_status{instance=~\"vo-.*\"} == 1) or on() vector(0)",
     "legendFormat": " "
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(iMacExam_status{instance=~\"vo-.*\"} == 0) or on() vector(0)",
     "legendFormat": " "
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(iMacService_status{job=\"iMacs\",instance=~\"vo-.*\",service=\"ldap\"} == 1) or on() vector(0)",
     "legendFormat": " "
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(iMacService_status{job=\"iMacs\",instance=~\"vo-.*\",service=\"ldap\"} == 0) or on() vector(0)",
     "legendFormat": " "
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(up{job=\"iMacs\",instance=~\"vo-.*\"} == 0) or on() vector(0)",
     "legendFormat": " "
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(up{job=\"iMacs\",instance=~\"vo-.*\"}) or on() vector(0)",
     "legendFormat": " "
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 15 },
   "options": {
    "content": "<center>\n    <h1>OXYGEN</h1>\n</center>"
   }
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(iMacExam_status{instance=~\"ox-.*\"} == 1) or on() vector(0)",
     "legendFormat": " "
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(iMacExam_status{instance=~\"ox-.*\"} == 0) or on() vector(0)",
     "legendFormat": " "
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(iMacService_status{job=\"iMacs\",instance=~\"ox-.*\",service=\"ldap\"} == 1) or on() vector(0)",
     "legendFormat": " "
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(iMacService_status{job=\"iMacs\",instance=~\"ox-.*\",service=\"ldap\"} == 0) or on() vector(0)",
     "legendFormat": " "
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(up{job=\"iMacs\",instance=~\"ox-.*\"} == 0) or on() vector(0)",
     "legendFormat": " "
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(up{job=\"iMacs\",instance=~\"ox-.*\"}) or on() vector(0)",
     "legendFormat": " "
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 17 },
   "options": {
    "content": "<center>\n    <h1>SUPERNOVA</h1>\n</center>"
   }
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(iMacExam_status{instance=~\"su-.*\"} == 1) or on() vector(0)",
     "legendFormat": " "
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(iMacExam_status{instance=~\"su-.*\"} == 0) or on() vector(0)",
     "legendFormat": " "
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(iMacService_status{job=\"iMacs\",instance=~\"su-.*\",service=\"ldap\"} == 1) or on() vector(0)",
     "legendFormat": " "
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(iMacService_status{job=\"iMacs\",instance=~\"su-.*\",service=\"ldap\"} == 0) or on() vector(0)",
     "legendFormat": " "
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(up{job=\"iMacs\",instance=~\"su-.*\"} == 0) or on() vector(0)",
     "legendFormat": " "
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(up{job=\"iMacs\",instance=~\"su-.*\"}) or on() vector(0)",
     "legendFormat": " "
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 19 },
   "options": {
    "content": "<center>\n    <h1>ATRIUM</h1>\n</center>"
   }
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(iMacExam_status{instance=~\"am-.*\"} == 1) or on() vector(0)",
     "legendFormat": " "
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(iMacExam_status{instance=~\"am-.*\"} == 0) or on() vector(0)",
     "legendFormat": " "
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(iMacService_status{job=\"iMacs\",instance=~\"am-.*\",service=\"ldap\"} == 1) or on() vector(0)",
     "legendFormat": " "
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(iMacService_status{job=\"iMacs\",instance=~\"am-.*\",service=\"ldap\"} == 0) or on() vector(0)",
     "legendFormat": " "
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(up{job=\"iMacs\",instance=~\"at-.*\"} == 0) or on() vector(0)",
     "legendFormat": " "
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(up{job=\"iMacs\",instance=~\"am-.*\"}) or on() vector(0)",
     "legendFormat": " "
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 21 },
   "options": {
    "content": "<center>\n    <h1>PLASMA</h1>\n</center>"
   }
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(iMacExam_status{instance=~\"pl-.*\"} == 1) or on() vector(0)",
     "legendFormat": " "
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(iMacExam_status{instance=~\"pl-.*\"} == 0) or on() vector(0)",
     "legendFormat": " "
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(iMacService_status{job=\"iMacs\",instance=~\"pl-.*\",service=\"ldap\"} == 1) or on() vector(0)",
     "legendFormat": " "
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(iMacService_status{job=\"iMacs\",instance=~\"pl-.*\",service=\"ldap\"} == 0) or on() vector(0)",
     "legendFormat": " "
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(up{job=\"iMacs\",instance=~\"pl-.*\"} == 0) or on() vector(0)",
     "legendFormat": " "
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(up{job=\"iMacs\",instance=~\"pl-.*\"}) or on() vector(0)",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Cluster lists",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Mirage",
     "type": "table",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 24 },
     "targets": [
      {
       "expr": "iMacExam_status{instance=~\"mi-.*\"}"
      },
      {
       "expr": "iMacService_status{instance=~\"mi-.*\",service=\"krb\"}"
      }
     ]
    },
    {
     "title": "Atlantis",
     "type": "table",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 24 },
     "targets": [
      {
       "expr": "iMacExam_status{instance=~\"at-.*\"}"
      },
      {
       "expr": "iMacService_status{instance=~\"at-.*\",service=\"ldap\"}"
      }
     ]
    },
    {
     "title": "Oasis",
     "type": "table",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 37 },
     "targets": [
      {
       "expr": "iMacExam_status{instance=~\"oa-.*\"}"
      },
      {
       "expr": "iMacService_status{instance=~\"oa-.*\",service=\"ldap\"}"
      }
     ]
    },
    {
     "title": "Illusion",
     "type": "table",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 37 },
     "targets": [
      {
       "expr": "iMacExam_status{instance=~\"il-.*\"}"
      },
      {
       "expr": "iMacService_status{instance=~\"il-.*\",service=\"ldap\"}"
      }
     ]
    },
    {
     "title": "Galaxy",
     "type": "table",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 50 },
     "targets": [
      {
       "expr": "iMacExam_status{instance=~\"ga-.*\"}"
      },
      {
       "expr": "iMacService_status{instance=~\"ga-.*\",service=\"ldap\"}"
      }
     ]
    },
    {
     "title": "Void",
     "type": "table",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 50 },
     "targets": [
      {
       "expr": "iMacExam_status{instance=~\"vo-.*\"}"
      },
      {
       "expr": "iMacService_status{instance=~\"vo-.*\",service=\"ldap\"}"
      }
     ]
    },
    {
     "title": "Oxygen",
     "type": "table",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 63 },
     "targets": [
      {
       "expr": "iMacExam_status{instance=~\"ox-.*\"}"
      },
      {
       "expr": "iMacService_status{instance=~\"ox-.*\",service=\"ldap\"}"
      }
     ]
    },
    {
     "title": "Super nova",
     "type": "table",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 63 },
     "targets": [
      {
       "expr": "iMacExam_status{instance=~\"su-.*\"}"
      },
      {
       "expr": "iMacService_status{instance=~\"su-.*\",service=\"ldap\"}"
      }
     ]
    },
    {
     "title": "Atrium",
     "type": "table",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 76 },
     "targets": [
      {
       "expr": "iMacExam_status{instance=~\"am-.*\"}"
      },
      {
       "expr": "iMacService_status{instance=~\"am-.*\",service=\"ldap\"}"
      }
     ]
    },
    {
     "title": "Plasma",
     "type": "table",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 76 },
     "targets": [
      {
       "expr": "iMacExam_status{instance=~\"pl-.*\"}"
      },
      {
       "expr": "iMacService_status{instance=~\"pl-.*\",service=\"ldap\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Alert",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "ExamUsb/SdStorage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "iMacExamStorage_status" }
     ]
    }
   ]
  }
 ]
}